parameter:

  github:
    github_account: cifren@msn.com
    github_secret: plapodwoainjagbwnaodiopONUnad

  youtrack:
    url: "https://cospirit.myjetbrains.com/youtrack/api"
    token: "Bearer perm:RnJhbmNpc19MZWNvcQ==.R2h5dA==.d9qeAMnrZ2V8JGs7DGICy6aijn3wWg"
    

