version: "3.6"

services:
  go:
    image: ghyt
    build: ./
    ports:
      - "5000:9000"
    volumes:
      - ./:/go
    command: ["gin", "--port", "9000", "--appPort", "9001", "run", "main.go"]

  ngrok:
    image: wernight/ngrok